In [1]:
pip install tensorflow

  Using cached tensorflow-2.11.0-cp38-cp38-win_amd64.whl (1.9 kB)
Note: you may need to restart the kernel to use updated packages.


## IMPORTING THE LIBRARIES

In [2]:
import numpy as np
import pandas as pd 
import tensorflow as tf

In [3]:
tf.__version__

'2.11.0'

## IMPORTING THE DATASET

In [6]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [8]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [9]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [10]:
print(y)

[1 0 1 ... 1 1 0]


In [11]:
print(dataset.isnull().sum())
# there is no null values in this dataset.

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64


## LABEL ENCODING IN DATASET 

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [13]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [15]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## SPLITTING THE DATA INTO TRAINING AND TEST SET 

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

## FEATURE SCALING

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# BUILDING THE ANN

## INITIALIZING THE ANN

In [22]:
ann = tf.keras.models.Sequential()
# Sequential initialize the sequential layer of artificial nueral network.

In [23]:
# adding the input layer and the first hidden layer 
# dense class is the famous library in pytorch as well as tensorflow
# gives an way to add fully connected layer in neural networks
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))

In [24]:
# second hidden layer 
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))

In [25]:
# output layer
ann.add(tf.keras.layers.Dense(units = 1,activation='sigmoid'))

## TRAINING THE ARTIFICIAL NEURAL NETWORK 

#### Optimizers are algorithms or methods used to change the attributes of your neural network such as weights and learning rate
#### in order to reduce the losses.

### COMPILING THE ANN

In [26]:
ann.compile(optimizer='adam',loss= 'binary_crossentropy', metrics=['accuracy'])

In [27]:
# Training the ANN on the training set
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
235/235 [==============================] - 5s 2ms/step - loss: 0.5413 - accuracy: 0.7963
Epoch 2/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4838 - accuracy: 0.7963
Epoch 3/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4614 - accuracy: 0.7963
Epoch 4/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4485 - accuracy: 0.7963
Epoch 5/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4397 - accuracy: 0.7963
Epoch 6/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4339 - accuracy: 0.7963
Epoch 7/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4304 - accuracy: 0.7963
Epoch 8/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4284 - accuracy: 0.8048
Epoch 9/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4265 - accuracy: 0.8128
Epoch 10/100
235/235 [==============================] - 0s 2ms/step - loss: 0.4252 - accura

235/235 [==============================] - 0s 2ms/step - loss: 0.3358 - accuracy: 0.8635
Epoch 82/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3361 - accuracy: 0.8635
Epoch 83/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3357 - accuracy: 0.8627
Epoch 84/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3357 - accuracy: 0.8635
Epoch 85/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3356 - accuracy: 0.8629
Epoch 86/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3354 - accuracy: 0.8641
Epoch 87/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3355 - accuracy: 0.8637
Epoch 88/100
235/235 [==============================] - 0s 2ms/step - loss: 0.3356 - accuracy: 0.8624
Epoch 89/100
235/235 [==============================] - 1s 2ms/step - loss: 0.3360 - accuracy: 0.8640
Epoch 90/100
235/235 [==============================] - 1s 2ms/step - loss: 0.3352 - accuracy: 

### Predicting the value on the basis of the test case given

In [28]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 3s 3s/step
[[False]]


In [29]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

79/79 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Checking the score or accuracy of the model by making the confusion matrix. 

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1895   96]
 [ 249  260]]


0.862